site_name: SQL DS Cache

repo_name: "Fork on GitHub"
repo_url: "https://github.com/oap-project/sql-ds-cache.git"
edit_uri: ""


nav:
  - User Guide: User-Guide.md
  - Advanced Configuration: Advanced-Configuration.md
  - OAP Installation Guide: OAP-Installation-Guide.md
  - OAP Developer Guide: OAP-Developer-Guide.md
  - Developer Guide: Developer-Guide.md
  - Version Selector: "../"



theme: readthedocs


plugins:
  - search
  - mkdocs-versioning:
      version: 1.2.0
      exclude_from_nav: ["image", "js", "css", "fonts", "img"]

