name: APE CPP CI

on:
  push:
    paths:
      - 'oap-ape/ape-native/**'
      - '.github/workflows/ape_cpp.yaml'
  pull_request:
    paths:
      - 'oap-ape/ape-native/**'
      - '.github/workflows/ape_cpp.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get CMake
        uses: lukka/get-cmake@v3.19.2
      - name: install python
        uses: actions/setup-python@v1
      # - name: run cpp lint
      #  run: cd oap-ape/ape-native/; python3 ./build-support/run_cpplint.py --cpplint_binary ./build-support/cpplint.py --source_dir ./src/
      - name: install clang-format
        run: sudo apt-get install clang-format -y
      - name: run clang-format check
        run: cd oap-ape/ape-native/; python3 ./build-support/run_clang_format.py --clang_format_binary clang-format --source_dir ./src/
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: install arrow
        run: ci_scripts/install_arrow.sh
      - name: install APE dependency
        run: ci_scripts/install_APE_dependency.sh
      - name: build ape cpp
        run: cd oap-ape/ape-native; mkdir build; cd build; cmake ..; make -j2

