name: APE Java CI

on:
  push:
    paths:
      - 'oap-ape/ape-java/**'
      - '.github/workflows/ape_java.yaml'
  pull_request:
    paths:
      - 'oap-ape/ape-java/**'
      - '.github/workflows/ape_java.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }} # todo: which pom.xml?
          restore-keys: ${{ runner.os }}-m2
      - name: pmem-common dependency
        run: cd /tmp; git clone https://github.com/oap-project/pmem-common.git; cd pmem-common/; git checkout branch-1.1-spark-3.x; mvn install -am -q -DskipTests
      - name: Build with Maven
        run: cd oap-ape/ape-java; mvn clean package -am --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn