name: APE CPP CI

on:
  push:
    paths:
      - 'oap-ape/**'
      - '.github/workflows/ape_cpp.yaml'
  pull_request:
    paths:
      - 'oap-ape/**'
      - '.github/workflows/ape_cpp.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get CMake
        uses: lukka/get-cmake@v3.19.2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: install arrow
        run: ci_scripts/install_arrow.sh
      - name: install APE dependency
        run: ci_scripts/install_APE_dependency.sh
      - name: build ape cpp
        run: cd oap-ape/ape-native; mkdir build; cd build; cmake ..; make -j2

